### ISSUE TITLE
invalid credit card numbers

### ISSUE THREAD

**Issue by typekpb** [syscrusher/fake#2]
having:

```
package main

import (
    "fmt"
    "github.com/syscrusher/fake"
)

func main() {
    fmt.Println(fake.CreditCardNum(""))
}
```

results in something like: `6011`
which doesn't seem to be a valid credit card number.

I'd expect it to match regex: `^[0-9]{4}(-[0-9]{4}){3}$`

**Comment by syscrusher** [comment]
Confirmed, acknowledged, will be patched shortly. Thanks for reporting!

**Comment by syscrusher** [comment]
Fixed. Thanks again for reporting.

**Comment by typekpb** [comment]
thanks!
